name: Deploy GH Pages

on:
  push: 
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - uses: actions/checkout@v3

      # setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # install dependencies
      - name: Install dependencies
        run: npm install

      # build project
      - name: Build project
        run: npm run build

      # deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
